### PR TITLE
asu: device and default package input

### PR DESCRIPTION
**Pull request by mwarning**
Use separate fields for the device and default packages. This is meant to improve attention to what packages might brick the device.

### CODE REVIEW

**Comment by mwarning** [comment]
packages

**Comment by itsthejb** [comment]
Looks good, yes! Thanks for doing this

**Comment by aparcar** [comment]
I'm not sure this is the right way. Looking at your screenshot I see packages that can be removed without any bricking in both boxes (kmod-usb2, luci, ppp...) but at the same time, for another device, it would be possible that the first box contains a Kernel module to handle ethernet or WiFi, meaning a removal "bricks" the device.

How about keeping a single box but showing a warning message when the user removes ANY of the default packages? Like one may add `vim` or some LuCI app without the warning, but when starting to remove default packages something pops up like "Please be careful when removing default packages, this may render your device unable to boot"

**Comment by itsthejb** [comment]
@mwarning Thanks for doing this!

I agree with @aparcar that the current concept wouldn't solve the class of problem that I (at least) encountered; there are indeed packages that could be removed and cause a bricking from both boxes. I believe that the goal is to preserve full customization, but at the same time at least warn the user that they may have make a dangerous edit

I agree that @aparcar's solution may also be viable

**Comment by mwarning** [comment]
idea rejected so far

**Comment by itsthejb** [comment]
I suspect I'll be using https://openwrt.org/docs/guide-user/installation/attended.sysupgrade going forward

**Pull request closed without merging**
